# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: repo

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: Canary Demo ACR
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile
    tags: |
      $(Build.BuildId)