apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        # Replace <your-container-registry> with your actual container registry
        image: <your-container-registry>.azurecr.io/sampleapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
      # imagePullSecrets:
      # - name: my-acr-secret